services:
  - type: web
    name: translate-backend
    env: python
    plan: free
    root: translate
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.server.api:app --host 0.0.0.0 --port $PORT
    envVars: []
